name: mybook_library
description: A Flutter project to manage a personal book library.

publish_to: 'none' # Remove this line if you plan to publish the package.

version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  uuid: ^3.0.6
  shared_preferences: ^2.0.13
  sqflite: ^2.0.0+4
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
  
    - assets/images/book-library-background.png
